### ISSUE TITLE
SDL3 ABI Checklist

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FNA3D#206]
- [ ] Add FNA3D_DRIVER_SDL define to visualc/Xcode
- [ ] BUILD_SDL3 defaults to ON
- [ ] Deprecate Vulkan, close all Vulkan issues

**Comment by flibitijibibo** [comment]
Updated visualc just now, so only Xcode needs updating at this point.
